
services:
  ai-server:
    init: true
    container_name: ai-server
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    build:
      context: ./ai-server
      dockerfile: Dockerfile  # 아래에 Dockerfile 예시 참고
    volumes:
      - ./ai-server/project:/project
    ports:
      - "80:8000"  # 호스트의 8000 포트를 컨테이너의 8000 포트

  ai-preprocessing:
    init: true
    container_name: ai-preprocessing
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    build:
      context: ./ai-preprocessing
      dockerfile: Dockerfile  # 아래에 Dockerfile 예시 참고
    volumes:
      - ./ai-preprocessing/project:/project