FROM jeongtj/langchain-rag

WORKDIR /project

# COPY requirements.txt /project/
# COPY entrypoint.sh /home/entrypoint.sh

# RUN pip install -r requirements.txt
# RUN chmod +x /home/entrypoint.sh


# ENTRYPOINT [ "/home/entrypoint.sh" ]
