name: Continuous Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 수동 트리거 옵션 추가

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via direct SSH command
        run: |
          # SSH 키 파일 생성
          echo "${{ secrets.PROD_SSH_KEY }}" > deploy_key.pem
          chmod 400 deploy_key.pem
          
          # SSH 연결 및 명령어 실행 (StrictHostKeyChecking=no로 호스트 키 확인 건너뛰기)
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${{ secrets.PROD_USERNAME }}@${{ secrets.PROD_HOST }} '
            cd ~/ai-server-test
            git remote update
            git checkout main
            git pull origin main
            make
          '
          
          # 키 파일 삭제
          rm deploy_key.pem
